### PR TITLE
PieceEval split to a per-piece basis

### PR DESCRIPTION
**Pull request by jhonnold**
Bench: 7899386

ELO   | 6.25 +- 6.29 (95%)
SPRT  | 8.0+0.08s Threads=1 Hash=16MB
LLR   | 2.95 (-2.94, 2.94) [-5.00, 0.00]
GAMES | N: 5840 W: 1509 L: 1404 D: 2927

### CODE REVIEW

**Comment by tissatussa** [comment]
what does this mean ? : _"deleted the eval-by-piece branch 5 days ago"_ is a piece of code merged into main ? What do you state by "eval by piece" ?  Do i find a description or should i read its functionality in your code -- i click "Files Changed 2" ?  i'm new to such GitHub issues ..

**Comment by jhonnold** [comment]
So because I've merged the code into the `dev` branch, I'm deleting the git branch that I did the original work on since it's no longer necessary.

Evaluation by piece in this case is call the `EvaluatePiece` method on a per-piece basis, rather than just once and looping through each piece individually. To see individual file changes, click on the 4th tab at the top which is "Files Changed".

**Comment by tissatussa** [comment]
ok, and i guess the overall functionality remained the same .. it's only a rewrite into a more robust architecture ?  (i'm a simple programmer myself .. no C).  Should it be handy, for contributers and also yourself, to add such description lines to a commit ?  Or is that too much a fuzz ?

**Comment by jhonnold** [comment]
Overall functionality did remain the same. This change was implemented to allow future ideas as well as a speed increase.

This is a personal project, I'm not interested in writing more than I have to for it.

**Comment by tissatussa** [comment]
just what i thought .. that's ok - thanks!

i watch your developments and Weiss' .. you collaborate ?  I also posted some issue there.

**Comment by jhonnold** [comment]
We do collaborate. I've reviewed all of Weiss multiple times. Terje has probably looked at tiny portions of Berserk before stopping due to it's spaghetti style.

**Comment by tissatussa** [comment]
Terje created MPV recently .. i proposed some advantages and assisted .. it works OK !  I'm not aware of any spag code .. ha!
I'm testing curious positions, mainly with MPV in SCID and some own GUI for UCI engines, i'm preparing to write an "issue" about a typical closed centre position with a Q sac : i let many engines play, with enough time, to discover patterns .. I also see you forked Ethereal .. i read that project stopped, i have some latest v12.75 NNUE and some v12.88 (?), all on Linux .. Ethereal is special, i see many coders use parts from it .. but using CuteChess Ethereal keeps disconnecting now and then (mostly when it's already lost) .. are coders continuing Ethereal ?
( btw. i this a proper place to discuss such subjects, or shall we create an issue for it ? )

**Comment by jhonnold** [comment]
This is not a proper place to discuss this topic. If you wish to chat with me directly, we can communicate on Discord or anything similar. If you wish to ask questions to the chess engine community as a whole, talkchess is the probably the place to go.

**Comment by tissatussa** [comment]
i mostly use email, also with other engine programmers .. is that OK with you ?

**Comment by jhonnold** [comment]
> 
> 
> i mostly use email, also with other engine programmers .. is that OK with you ?

That's fine as well.

**Comment by tissatussa** [comment]
is it smart to post our email addresses here ?  I see no message feature on this GitHub website ..

**Pull request merged**
