### PR TITLE
King and Pawn NN

### PR DESCRIPTION
**Pull request by jhonnold**
Bench: 6767718

ELO   | 20.74 +- 9.63 (95%)
SPRT  | 8.0+0.08s Threads=1 Hash=8MB
LLR   | 3.00 (-2.94, 2.94) [-1.00, 4.00]
GAMES | N: 2432 W: 663 L: 518 D: 1251

ELO   | 8.40 +- 5.35 (95%)
SPRT  | 40.0+0.40s Threads=1 Hash=64MB
LLR   | 2.95 (-2.94, 2.94) [-1.00, 4.00]
GAMES | N: 5752 W: 1095 L: 956 D: 3701

### CODE REVIEW

**Comment by tissatussa** [comment]
is this the result of a new approach ?  Training NNs with piece combos ?  I never saw such idea / function in the chess engine world .. Are your NNs unique ?

**Comment by tissatussa** [comment]
Btw. how can we understand the training of NNs ? Can such NN then be queried for certain position types ? Or does a search-by-depth also exist in these trained NNS ?

**Comment by jhonnold** [comment]
This NN just sits atop my current evaluation function and helps correct it. King and Pawn was chosen as it's result is cached in a kp-hash table which balances the cost of calculation. This idea is not new, Ethereal has done a King and Pawn net. Another engine of note is Tomitank, which currently has a small internal net that corrects it's entire evaluation function.

My nets are trained alongside the rest of my evaluation. The tuning code can be found in my [tuner](https://github.com/jhonnold/berserk/blob/main/src/tuner/tune.c#L856).

**Comment by tissatussa** [comment]
So maybe any piece combo can give a unique NN by training it with special positions ?  Here, i understand your "..balances the cost of calculation.." - can you elaborate on this ?  I imagine a set of choosen and composed positions to feed / train a NN ?

**Comment by jhonnold** [comment]
> So maybe any piece combo can give a unique NN by training it with special positions

Yes, but once you start doing lots of combinations, why not just feed all pieces into a single net. King and Pawn net is cached and has a hit rate of 89.5% which is one of it's largest strengths.

> ..balances the cost of calculation..

Forward prop in a NN is expensive (lots of flops) so when I say balance, I meant that the cachability is a large benefit.

> I imagine a set of choosen and composed positions to feed / train a NN

I did not change my dataset (yet). I'm currently looking at newer/larger datasets generated from the current `dev` version of Berserk.

**Comment by tissatussa** [comment]
> newer/larger datasets generated from the current dev version of Berserk

this is the (only) self-learning AlphaZero idea ?
[rest is clear]

**Comment by jhonnold** [comment]
I don't think this is what AlphaZero does. I'm just following a standard pattern of generating FENs for tuning. [See here](https://www.chessprogramming.org/Texel's_Tuning_Method#Method)

**Pull request merged**
