### PR TITLE
Support UCI ponder

### PR DESCRIPTION
**Pull request by jhonnold**
Bench: 7435016

ELO   | 3.26 +- 4.37 (95%)
SPRT  | 8.0+0.08s Threads=1 Hash=16MB
LLR   | 2.95 (-2.94, 2.94) [-5.00, 0.00]
GAMES | N: 9176 W: 1781 L: 1695 D: 5700

### CODE REVIEW

**Comment by tissatussa** [comment]
since a few days i "watch" all your activities and so i just received a notification by email about this issue : Support UCI ponder (#232) .. can i download & compile this DEV version ?  Is Berserk really going to have a ponder function ?

**Comment by jhonnold** [comment]
> 
> 
> since a few days i "watch" all your activities and so i just received a notification by email about this issue : Support UCI ponder (#232) .. can i download & compile this DEV version ? Is Berserk really going to have a ponder function ?

Berserk now supports `ponder` on it's `dev` branch. Feel free to use a local compile if you want more immediate access to it.

```
git clone https://github.com/jhonnold/berserk
cd berserk/src
git checkout dev
make
```

**Comment by tissatussa** [comment]
it seems i was able to compile a DEV that way : 

```
roelof@roelof-SATELLITE-C855-226:~/Downloads/tmp3$ git clone https://github.com/jhonnold/berserk
Cloning into 'berserk'...
remote: Enumerating objects: 2198, done.
remote: Counting objects: 100% (525/525), done.
remote: Compressing objects: 100% (394/394), done.
remote: Total 2198 (delta 397), reused 236 (delta 131), pack-reused 1673
Receiving objects: 100% (2198/2198), 13.28 MiB | 10.19 MiB/s, done.
Resolving deltas: 100% (1703/1703), done.
roelof@roelof-SATELLITE-C855-226:~/Downloads/tmp3$ cd berserk/src/
roelof@roelof-SATELLITE-C855-226:~/Downloads/tmp3/berserk/src$ git checkout dev
Branch 'dev' set up to track remote branch 'dev' from 'origin'.
Switched to a new branch 'dev'
roelof@roelof-SATELLITE-C855-226:~/Downloads/tmp3/berserk/src$ make
gcc -O3 -std=gnu11 -Wall -Wextra -Wshadow -flto -march=native -DNDEBUG -g *.c pyrrhic/tbprobe.c noobprobe/noobprobe.c -lm -lpthread -DPOPCOUNT -msse -msse3 -mpopcnt -o berserk
roelof@roelof-SATELLITE-C855-226:~/Downloads/tmp3/berserk/src$ 

```

i never did a "git checkout dev" but it created a working binary ..

in CuteChess however, i see no pondering like other engines do it : the values for Pondermove and Ponderhit remain empty and no calculation fluctuation is displayed while the other engine is 'thinking' !?  I guess you need to add some option(s) in the UCI command for it to work in CuteChess.

**Comment by jhonnold** [comment]
Thanks, I'll look into that.

**Pull request merged**
