### PR TITLE
Equality of (PHASE_VALUES, MATERIAL_VALUES) = ( Increase NPS , Better Score)

### PR DESCRIPTION
**Pull request by TheDarkKnightRise**
```c
const int MATERIAL_VALUES[7] = {100, 300, 300, 500, 1000, 0, 0};

const int PHASE_VALUES[6] = {0, 3, 3, 5, 10, 0};

```

### CODE REVIEW

**Comment by jhonnold** [comment]
First, this is a functional engine change. It will need to be tested using SPRT on OpenBench.
Second, how did this increase NPS?
Third, why do these values need to align? One is for evaluation scaling another is for history adjustment in move scoring. Even [see](https://github.com/jhonnold/berserk/blob/main/src/see.c#L27) has a third set of these values.

**Comment by tissatussa** [comment]
does this mean such change will be in the main branch ? It might change the playing style hugely .. but first all needs to be tested i guess ..

**Comment by TheDarkKnightRise** [comment]
**_Equality of (PHASE_VALUES, MATERIAL_VALUES)_** decrease breaking alpha-beta pruning that Increases branch search & NPS

It will need to be tested on OpenBench , But I just tested some position in my local computer 

### _before_
```js
position fen r3k2r/p1ppqpb1/bn2pnp1/3PN3/1p2P3/2N2Q1p/PPPBBPPP/R3K2R w KQkq - 0 1
info depth 18 seldepth 32 multipv 1 score cp -139 nodes 605999 nps 1688019 hashfull 267 tbhits 0 time 359 pv e2a6 b4c3 d2c3 h3g2 f3g2 e6d5 e1g1 d5e4 a6b7 a8b8 b7e4 f6e4 g2e4 d7d6 e4c6 e8f8 e5f3 e7d7 c6d7 b6d7 c3g7 f8g7 b2b3 d7f8 f3d4 h8h4
```
### _after_
```js
position fen r3k2r/p1ppqpb1/bn2pnp1/3PN3/1p2P3/2N2Q1p/PPPBBPPP/R3K2R w KQkq - 0 1
info depth 18 seldepth 40 multipv 1 score cp -204 nodes 1808518 nps 1961516 hashfull 751 tbhits 0 time 922 pv e2a6 h3g2 f3g2 b4c3 d2c3 e6d5 e1g1 d5e4 a6b7 a8b8 b7e4 f6e4 g2e4 d7d6 e4c6 e8f8 e5g4 g7c3 c6c3 h8h5 c3g3 e7g5 f2f4 g5c5 g3f2 a7a5
```


> * Even [see](https://github.com/jhonnold/berserk/blob/main/src/see.c#L27) has a third set of these values.

probably changing  [see](https://github.com/jhonnold/berserk/blob/main/src/see.c#L27) values also can improve engine search

**Comment by jhonnold** [comment]
> Equality of (PHASE_VALUES, MATERIAL_VALUES) decrease breaking alpha-beta pruning that Increases branch search & NPS

Why does this improve alpha-beta? How in the world did this increase NPS?

> I just tested some position in my local computer

Testing a singular position for anything is not justification.

> probably changing [see](https://github.com/jhonnold/berserk/blob/main/src/see.c#L27) values also can improve engine search

Considering these have been tuned using an external tool, that seems unlikely.

---

If you want this patch to be tested on OB I need justification on why these values should match as *they are unrelated*. Lots of people use phase values of `{0,1,1,2,4}`, but no one uses material values `{100, 100, 100, 200, 400}`.

In all reality these values could probably use a tune via [CTT](https://chess-tuning-tools.readthedocs.io), which if you did, I would be happy to test on OB.

**Comment by TheDarkKnightRise** [comment]
> Lots of people use phase values of `{0,1,1,2,4}`, but no one uses material values `{100, 100, 100, 200, 400}`.

No , It is only valid for these phase values `{3, 3, 5, 10}`  , Not true for other values

> Why does this improve alpha-beta?

Reducing the material values ​​reduces the probability of breaking alpha-beta

>In all reality these values could probably use a tune via [CTT](https://chess-tuning-tools.readthedocs.io/), which if you did,

I am asking @tissatussa  to do this .  this material values normalize score which improving  ELO rating 

> Testing a singular position for anything is not justification.

It needs something like fishtest

**Comment by tissatussa** [comment]
> I am asking @tissatussa to do this ..

i'm surprised to find my handle here .. i'm willing to help somehow, seems interesting, but i never used CTT (but CuteChess-Cli yes) .. i'm a programmer, but not yet of any chess engine, just a user, mostly viewing engines play in CuteChess (GUI) from certain starting positions to see their style and patterns .. i never did many very fast games, mostly 10m+2s or even slower .. i'm an experienced chess player though, how can i help ?

**Comment by TheDarkKnightRise** [comment]
Girl in a jacket

**Comment by TheDarkKnightRise** [comment]
```
info depth 1 seldepth 1 multipv 1 score cp 433 nodes 10 nps 10000 hashfull 0 tbhits 0 time 0 pv a3b4
info depth 2 seldepth 5 multipv 1 score cp 447 nodes 24 nps 24000 hashfull 0 tbhits 0 time 0 pv a3b4 e5f3 e2f3 a6f1
info depth 3 seldepth 5 multipv 1 score cp 447 nodes 41 nps 2562 hashfull 0 tbhits 0 time 16 pv a3b4 e5f3 e2f3 a6f1
info depth 4 seldepth 7 multipv 1 score cp 395 nodes 192 nps 12000 hashfull 0 tbhits 0 time 16 pv f3g2 g8h8 a3b4 a5b4 h4h5
info depth 5 seldepth 7 multipv 1 score cp 486 nodes 428 nps 26750 hashfull 0 tbhits 0 time 16 pv f3g2 g8g7 c3d5 c6d5 a3b4
info depth 6 seldepth 9 multipv 1 score cp 153 nodes 1597 nps 99812 hashfull 2 tbhits 0 time 16 pv f3d5 c6d5 a3b4 e6h3 b4b5
info depth 7 seldepth 10 multipv 1 score cp 153 nodes 1828 nps 114250 hashfull 2 tbhits 0 time 16 pv f3d5 c6d5 a3b4 e6h3 b4b5
info depth 8 seldepth 10 multipv 1 score cp 170 nodes 2261 nps 72935 hashfull 2 tbhits 0 time 31 pv f3d5 c6d5 a3b4 a5b4 c3d5 a6e2 d5c7
info depth 9 seldepth 13 multipv 1 score cp 255 nodes 3298 nps 106387 hashfull 3 tbhits 0 time 31 pv f3d5 c6d5 a3b4 a5b4 c3d5 a6e2 d2e2 e6d5 e2e4
info depth 10 seldepth 16 multipv 1 score cp 83 nodes 19158 nps 407617 hashfull 5 tbhits 0 time 47 pv a3b4 e5f3 e2f3 a6f1 c2c1 e6e1 c1e1 e8e1 b4a5 f1c4 g1g2 c4b3 a5a6
info depth 11 seldepth 18 multipv 1 score cp 83 nodes 22913 nps 487510 hashfull 5 tbhits 0 time 47 pv a3b4 e5f3 e2f3 a6f1 c2c1 e6e1 c1e1 e8e1 b4a5 f1c4 g1g2 c4b3 a5a6
info depth 12 seldepth 22 multipv 1 score cp 68 nodes 45381 nps 731951 hashfull 13 tbhits 0 time 62 pv a3b4 e5f3 e2f3 a6f1 c2c1 f1a6 b4a5 e6e1 c1e1 e8e1 g1g2
info depth 13 seldepth 22 multipv 1 score cp 91 nodes 58224 nps 746461 hashfull 16 tbhits 0 time 78 pv a3b4 e5f3 e2f3 a6f1 d2d1 a5b4 d1f1 b4c3 c2c3 d5d4 c3d4 e6b3 g1g2 b3d5 d4a4 d5c5
info depth 14 seldepth 26 multipv 1 score cp 81 nodes 190360 nps 1350070 hashfull 62 tbhits 0 time 141 pv f1c1 b4b8 c3a4 e6f6 f3g2 e5g4 e2e3 a6c8 a4c5 c8f5 c2c3 f6c3 c1c3 g4f6 c5a6 b8c8 a6c5
info depth 15 seldepth 30 multipv 1 score cp 91 nodes 420813 nps 1683252 hashfull 113 tbhits 0 time 250 pv f3g2 b4b8 c3a4 e6e7 a4c5 a6c8 f1c1 c8f5 c2c3 b8b5 a3a4 b5b4 d2d4 b4d4 c3d4 f5g4 d4e3 e5d7
info depth 16 seldepth 35 multipv 1 score cp 27 nodes 878724 nps 1939788 hashfull 232 tbhits 0 time 453 pv f3g2 b4b8 c3a4 e6e7 a4c5 a6c8 f1c1 c8f5 c2c3 b8b5 d2d4 e8b8 a3a4 b5b4 e2e3 h7h5 d4b4 b8b4 c1d1 e5g4
info depth 17 seldepth 35 multipv 1 score cp 68 nodes 926433 nps 1975336 hashfull 242 tbhits 0 time 469 pv f3g2 b4b8 c3a4 e6e7 a4c5 a6c8 e2e4 d5e4 c5e4 c8e6 f1e1 e6b3 c2c3 b3d5 d2e2 b8b3 c3a5 e8b8
info depth 18 seldepth 35 multipv 1 score cp 29 nodes 1396242 nps 2032375 hashfull 350 tbhits 0 time 687 pv a3b4 e5f3 e2f3 a6f1 c2b1 a5b4 c3d5 f1b5 d5e3 h7h5 b1c2 e6f6 g1g2 f6e5 f3f4 e5e4 c2e4 e8e4 g2f3 e4e8 d2d6 c6c5 e3d5
bestmove a3b4 ponder e5f3
```

**Comment by TheDarkKnightRise** [comment]
```
info depth 1 seldepth 1 multipv 1 score cp 433 nodes 10 nps 10000 hashfull 0 tbhits 0 time 0 pv a3b4
info depth 2 seldepth 5 multipv 1 score cp 447 nodes 24 nps 24000 hashfull 0 tbhits 0 time 0 pv a3b4 e5f3 e2f3 a6f1
info depth 3 seldepth 5 multipv 1 score cp 447 nodes 41 nps 41000 hashfull 0 tbhits 0 time 0 pv a3b4 e5f3 e2f3 a6f1
info depth 4 seldepth 7 multipv 1 score cp 395 nodes 192 nps 12000 hashfull 0 tbhits 0 time 16 pv f3g2 g8h8 a3b4 a5b4 h4h5
info depth 5 seldepth 7 multipv 1 score cp 486 nodes 428 nps 26750 hashfull 0 tbhits 0 time 16 pv f3g2 g8g7 c3d5 c6d5 a3b4
info depth 6 seldepth 9 multipv 1 score cp 153 nodes 1597 nps 99812 hashfull 2 tbhits 0 time 16 pv f3d5 c6d5 a3b4 e6h3 b4b5
info depth 7 seldepth 10 multipv 1 score cp 153 nodes 1828 nps 114250 hashfull 2 tbhits 0 time 16 pv f3d5 c6d5 a3b4 e6h3 b4b5
info depth 8 seldepth 10 multipv 1 score cp 170 nodes 2261 nps 70656 hashfull 2 tbhits 0 time 32 pv f3d5 c6d5 a3b4 a5b4 c3d5 a6e2 d5c7
info depth 9 seldepth 13 multipv 1 score cp 216 nodes 3233 nps 101031 hashfull 3 tbhits 0 time 32 pv f3d5 c6d5 a3b4
info depth 10 seldepth 17 multipv 1 score cp 89 nodes 22007 nps 468234 hashfull 4 tbhits 0 time 47 pv f3g2 b4b8 f1c1 e6f5 e2e4 e5f3 g2f3 f5f3 e4d5 c6c5 d5d6
info depth 11 seldepth 17 multipv 1 score cp 139 nodes 33558 nps 532666 hashfull 7 tbhits 0 time 63 pv f3g2 b4b8 c3a4 e6d6 a4c5 a6b5 f1d1 e5g4
info depth 12 seldepth 19 multipv 1 score cp 119 nodes 75535 nps 968397 hashfull 14 tbhits 0 time 78 pv f3g2 b4b8 c3a4 e5d7 f1d1 e6d6 e2e3 a6b5 a4c3 b5a6 e3e4 d7c5 e4d5
info depth 13 seldepth 22 multipv 1 score cp 75 nodes 186882 nps 1495056 hashfull 50 tbhits 0 time 125 pv f1c1 b4b8 c3a4 e6e7 a4c5 a6c8 c2c3 b8b5 d2d4 h7h5 d4f4 e7a7 f3h1 c8f5 h1g2
info depth 14 seldepth 26 multipv 1 score cp 62 nodes 279286 nps 1623755 hashfull 65 tbhits 0 time 172 pv f3g2 b4b8 c3a4 e6e7 a4c5 a6c8 f1c1 c8g4 a3a4 e5d7 c5d7 g4d7 e2e4 d5e4 g2e4 d7e6 c2c5 e7c5
info depth 15 seldepth 29 multipv 1 score cp 81 nodes 433268 nps 1733072 hashfull 91 tbhits 0 time 250 pv f3g2 b4b8 c3a4 e6e7 a4c5 a6c8 f1c1 a5a4 b3b4 e5c4 d2d4 e7e2 c2a4 c4e5 a4b3 e5g4 c1f1 c8f5 b3c3 g4e5 a3a4
info depth 16 seldepth 32 multipv 1 score cp 27 nodes 804715 nps 1977186 hashfull 186 tbhits 0 time 407 pv a3b4 e5f3 e2f3 a6f1 c2b1 a5b4 c3d5 f1b5 d5b4 b5e2 g1g2 e6f6 f3f4 f6c3 b1c2 c3b4 d2e2 e8e2 c2e2 b4b3
info depth 17 seldepth 32 multipv 1 score cp 20 nodes 925895 nps 1974189 hashfull 212 tbhits 0 time 469 pv f3g2 b4b8 c3a4 e6e7 a4c5 a6c8 e2e4 b8b5 f1c1 d5e4 c5e4 c8f5 a3a4 b5b4 d2e2 e8b8 c2c3 b4b3 c3a5 f5g4 e4f6 e7f6 e2e5 b3b2
info depth 18 seldepth 32 multipv 1 score cp 20 nodes 1048658 nps 1971161 hashfull 238 tbhits 0 time 532 pv f3g2 b4b8 c3a4 e6e7 a4c5 a6c8 e2e4 b8b5 f1c1 d5e4 c5e4 c8f5 a3a4 b5b4 d2e2 e8b8 c2c3 b4b3 c3a5 f5g4 e4f6 e7f6 e2e5 b3b2
bestmove f3g2 ponder b4b8
```

**Comment by TheDarkKnightRise** [comment]
... proves that this pull should be merge , bg2 is bestmove not axb4

**Comment by TheDarkKnightRise** [comment]
please compare in depth 18 with SF 15 NNUE and Berserk 10 NN 

**The best engine is the one that provides the bestmove in the shortest time**

**Comment by tissatussa** [comment]
> please compare in depth 18 with SF 15 NNUE and Berserk 10 NN

indeed SF 15 NNUE at depth 18 gives bestmove Bg2 (after less then 4 sec) .. but if axb4 would have been SF 15' bestmove at dp 18 and your test would also have resulted in that move, it should also be considered a good result, because my test points to 3 bestmoves at depth 30 ?

The best engine is the one that provides the bestmove in the shortest time

**Comment by TheDarkKnightRise** [comment]
image

Bg2 , White is silently better but Rc1 and axb4 position is equal , Bestmove is Bg2

**Comment by tissatussa** [comment]
> Bg2 , White is slightly better , but Rc1 and axb4 position is equal , Bestmove is Bg2

i can agree .. but i feel 0.19 is too low for conclusions .. couldn't specific test positions be used which have an uncommon / hidden bestmove for most engines / at lower depth ? I was stressing this idea in other GitHub Issues lately ..

**Comment by TheDarkKnightRise** [comment]
From a chess player view , Rc1 & axb4 are not good moves , because after Nxf3 it makes double pawn and in endgame can cause defeat 

 

I've given all my reasons and I'm waiting to @jhonnold opinion, but I'm sure this change will increase 10 Elo to blitz Rating

**Comment by tissatussa** [comment]
thanks for the position .. just giving feedback .. good luck with the new eval idea !

**Comment by TheDarkKnightRise** [comment]
@jhonnold , Did you test this branch using SPRT on OpenBench.?

**Comment by jhonnold** [comment]
I appreciate you attempting to improve Berserk, but your reasoning for this patch doesn't make sense and I'm not going to test this.

---

> Reducing the material values ​​reduces the probability of breaking alpha-beta

These values have absolutely no impact on evaluation scores, so how could they "break" alpha-beta?

> from a chess player point of view , Rc1 & axb4 are not good moves , because after Nxf3 it makes double pawn and in endgame can cause defeat

Hand-picking positions are **NOT JUSTIFICATION**.

**Comment by TheDarkKnightRise** [comment]
```
Stockfish 15 by the Stockfish developers (see AUTHORS file)
info depth 30 seldepth 43 multipv 1 score cp 12 nodes 25932593 nps 1078771 hashfull 1000 tbhits 0 time 24039 pv f3g2 b4b8 c3a4 e6e7 a4c5 a6c8 e2e4 b8b5 f1c1 d5e4 c5e4 c8f5 a3a4 b5d5 c2c3 e7d8 d2d5 c6d5 c1d1 e5g4 d1d5 d8d5 e4f6 g4f6 g2d5 f6d5 c3a5 f5e4 a5e1 e8e6 e1d1 e6f6 h4h5 e4f3 d1d3 g8g7 b3b4 f6f5
info depth 30 seldepth 41 multipv 2 score cp 6 nodes 25932593 nps 1078771 hashfull 1000 tbhits 0 time 24039 pv f1c1 e5f3 e2f3 b4b7 g1g2 b7e7 c3a4 a6c8 g3g4 h7h5 c2c6 h5g4 c6e6 g4f3 g2f3 c8e6 a4c5 e8b8 d2d4 e7c7 f3e3 b8b5 c5d3 c7b7 b3b4 a5b4 d4b4 b5b4 d3b4 b7b8 c1e1 d5d4 e3d4
info depth 30 seldepth 40 multipv 3 score cp 0 nodes 25932593 nps 1078771 hashfull 1000 tbhits 0 time 24039 pv a3b4 e5f3 e2f3 a6f1 c2c1 f1a6 b4a5 e6e1 c1e1 e8e1 g1g2 g8f8 b3b4 e1a1 b4b5 c6b5 c3d5 a1a5 d5c7 b5b4 d2b2 a6b7 b2b4 b7c6 b4c4 c6a4 c4d4 a4c6
bestmove f3g2 ponder b4b8
```

**Pull request closed without merging**
